[categories]
1.title = 'DNS Compromise'
1.description = 'Altering DNS records resulting in improper redirection.'
2.title = 'DNS Poisoning'
2.description = 'Falsifying domain server cache (cache poisoning).'
3.title = 'Fraud Orders'
3.description = 'Fraudulent orders.'
4.title = 'DDoS Attack'
4.description = 'Participating in distributed denial-of-service (usually part of botnet).'
5.title = 'FTP Brute-Force'
5.description = ''
6.title = 'Ping of Death'
6.description = 'Oversized IP packet.'
7.title = 'Phishing'
7.description = 'Phishing websites and/or email.'
8.title = 'Fraud VoIP'
8.description = '' 	
9.title = 'Open Proxy'
9.description = 'Open proxy, open relay, or Tor exit node.'
10.title = 'Web Spam'
10.description = 'Comment/forum spam, HTTP referer spam, or other CMS spam.'
11.title = 'Email Spam'
11.description = 'Spam email content, infected attachments, and phishing emails. Note: Limit comments to only relevent information (instead of log dumps) and be sure to remove PII if you want to remain anonymous.'
12.title = 'Blog Spam'
12.description = 'CMS blog comment spam.'
13.title = 'VPN IP'
13.description = 'Conjunctive category.'
14.title = 'Port Scan'
14.description = 'Scanning for open ports and vulnerable services.'
15.title = 'Hacking'
15.description = ''
16.title = 'SQL Injection'
16.description = 'Attempts at SQL injection.'
17.title = 'Spoofing'
17.description = 'Email sender spoofing.'
18.title = 'Brute-Force'
18.description = 'Credential brute-force attacks on webpage logins and services like SSH, FTP, SIP, SMTP, RDP, etc. This category is seperate from DDoS attacks.'
19.title = 'Bad Web Bot'
19.description = 'Webpage scraping (for email addresses, content, etc) and crawlers that do not honor robots.txt. Excessive requests and user agent spoofing can also be reported here.'
20.title = 'Exploited Host'
20.description = 'Host is likely infected with malware and being used for other attacks or to host malicious content. The host owner may not be aware of the compromise. This category is often used in combination with other attack categories.'
21.title = 'Web App Attack'
21.description = 'Attempts to probe for or exploit installed web applications such as a CMS like WordPress/Drupal, e-commerce solutions, forum software, phpMyAdmin and various other software plugins/solutions.'
22.title = 'SSH'
22.description = 'Secure Shell (SSH) abuse. Use this category in combination with more specific categories.'
23.title = 'IoT Targeted'
23.description = 'Abuse was targeted at an "Internet of Things" type device. Include information about what type of device was targeted in the comments.'