# Generated by Django 4.2.9 on 2024-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatortype',
            options={'verbose_name_plural': 'Indicator Types'},
        ),
        migrations.RemoveField(
            model_name='check',
            name='created_timestamp',
        ),
        migrations.AddField(
            model_name='check',
            name='last_modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
